---
apiVersion: v1
kind: Secret
metadata:
  name: nutanix-csi-storage-precheck-pe-secret
  namespace: kube-system
data:
  key: '{{printf "%s:%s:%s:%s" .Values.credentials.NUTANIX_ENDPOINT .Values.credentials.NUTANIX_PORT .Values.credentials.NUTANIX_USERNAME .Values.credentials.NUTANIX_PASSWORD | b64enc}}'

---
apiVersion: v1
kind: Secret
metadata:
  name: ntnx-secret
  namespace: kube-system
data:
  key: '{{printf "%s:%s:%s:%s" .Values.credentials.NUTANIX_ENDPOINT .Values.credentials.NUTANIX_PORT .Values.credentials.NUTANIX_USERNAME .Values.credentials.NUTANIX_PASSWORD | b64enc}}'
