/*
Copyright 2025 The KubeOne Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package helmchart

// fieldMapping maps the top-level fields of the addon render context
// (templateData) to their Helm .Values keys. The translation rewrites a
// template rooted at .Field into .Values.<key>, leaving any nested field or
// method references untouched.
var fieldMapping = map[string]string{
	"Config":                                   "config",
	"Params":                                   "params",
	"Certificates":                             "certificates",
	"Credentials":                              "credentials",
	"CustomCredentials":                        "customCredentials",
	"CredentialsCCM":                           "credentialsCCM",
	"CredentialsCCMHash":                       "credentialsCCMHash",
	"CCMClusterName":                           "ccmClusterName",
	"CalicoIptablesBackend":                    "calicoIptablesBackend",
	"DeployCSIAddon":                           "deployCSIAddon",
	"SnapshotterWebhookFailurePolicy":          "snapshotterWebhookFailurePolicy",
	"MachineControllerCredentialsEnvVars":      "machineControllerCredentialsEnvVars",
	"MachineControllerCredentialsHash":         "machineControllerCredentialsHash",
	"OperatingSystemManagerEnabled":            "operatingSystemManagerEnabled",
	"OperatingSystemManagerCredentialsEnvVars": "operatingSystemManagerCredentialsEnvVars",
	"OperatingSystemManagerCredentialsHash":    "operatingSystemManagerCredentialsHash",
	"RegistryCredentials":                      "registryCredentials",
	"Resources":                                "resources",
}

// valuesFile returns the default values.yaml content. KubeOne injects the full
// render context (config, certificates, credentials, etc.) at deploy time, so
// the checked-in values file intentionally carries no defaults and only serves
// as documentation of the available keys.
func valuesFile() string {
	return `# Generated by KubeOne. This chart renders the manifests of a KubeOne
# addon. At deploy time KubeOne injects the following values; they are not
# populated here because they depend on the live cluster configuration.
#
# config:                        # the KubeOneCluster configuration
# params: {}                     # addon params from addons.addons[].addon.params
# certificates: {}               # generated webhook TLS certificates
# credentials: {}                # cloud provider credentials
# customCredentials: {}          # user-provided custom credentials
# credentialsCCM: {}             # CCM-specific credentials
# credentialsCCMHash: ""         # hash of the CCM credentials
# ccmClusterName: ""             # name of the external CCM cluster
# calicoIptablesBackend: ""      # Auto | Legacy | NFT
# deployCSIAddon: false          # whether a CSI addon is deployed
# snapshotterWebhookFailurePolicy: "" # Fail | Ignore
# machineControllerCredentialsEnvVars: "" # pre-rendered credential env vars
# machineControllerCredentialsHash: ""
# operatingSystemManagerEnabled: false
# operatingSystemManagerCredentialsEnvVars: ""
# operatingSystemManagerCredentialsHash: ""
# registryCredentials: []        # containerd registry credentials
# resources: {}                  # templated resource names
`
}
