---
apiVersion: v1
kind: Secret
metadata:
  name: metrics-server-serving-cert
  namespace: kube-system
data:
  "cert.pem": |
{{.Values.certificates.MetricsServerCert | b64enc | indent 4}}
  "key.pem": |
{{.Values.certificates.MetricsServerKey | b64enc | indent 4}}
