---
apiVersion: v1
kind: Secret
metadata:
  name: vcloud-basic-auth
  namespace: kube-system
data:{{with .Values.credentials.VCD_USER}}
  username: {{. | b64enc}}{{end}}{{with .Values.credentials.VCD_PASSWORD}}
  password: {{. | b64enc}}{{end}}{{with .Values.credentials.VCD_API_TOKEN}}
  refreshToken: {{. | b64enc}}{{end}}
